package main

import "fmt"

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func main() {
	// simply calculate the Fibonacci number up to 4000000 and sum the even ones
	n := 4000000
	sum := 0
	prev := 1
	curr := 1
	for curr <= n {
		if curr%2 == 0 {
			sum += curr
		}
		prev, curr = curr, prev+curr
	}
	fmt.Println(sum)
}
